[general]
live_config_reload = true
working_directory = "/home/tommy/projects"

[window]
startup_mode = "Fullscreen"
opacity = 0.7
decorations = "None"

[scrolling]
history = 10000
multiplier = 10

[cursor]
style.shape = "Beam"
style.blinking = "On"
blink_interval = 300
blink_timeout = 0

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
