[general]
live_config_reload = true
working_directory = "/home/tommy/projects"
import = [
	#"~/.config/alacritty/themes/catppuccin-latte.toml",
	#"~/.config/alacritty/themes/catppuccin-frappe.toml",
	#"~/.config/alacritty/themes/catppuccin-macchiato.toml",
	"~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
opacity = 0.82
decorations = "None"

[scrolling]
history = 10000
multiplier = 10

[cursor]
style.shape = "Beam"
style.blinking = "On"
blink_interval = 300
blink_timeout = 0

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = true

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[font]
# Donwload from https://www.nerdfonts.com/font-downloads
normal = {family="UbuntuMonoNerdFont", style="Regular"}
bold = {family="UbuntuMonoNerdFont", style="Bold"}
italic = {family="UbuntuMonoNerdFont", style="Italic"}
bold_italic = {family="UbuntuMonoNerdFont", style="BoldItalic"}

